export interface ItemTypes {
    id: number,
    portrait: string,
    sprite: string,
    name: string,
    description: string,
    type: string,
    subtype: string,
    location: string,
    cardSlots: number,
    attack: number,
    defense: number,
    property: string,
    weight: number,
    weaponLevel: number,
    requiresLevel: number,
    buy: number,
    sell: number,
    usableBy: string[],
    script: Function[],
  }